name: OGProtocol-Minecraft
version: '1.0'
main: jaime.oGProtocolMinecraft.OGProtocolMinecraft
api-version: '1.21'
authors: [ Jaime ]
description: Software for OG Protocol authentication
commands:
  login:
    description: Login command
